spring:
  application:
    name: zuul-edge-server
  profiles:
    active: localhost
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service/
          predicates:
            - Path=/api/1.0/product/**
        - id: product-cache-service
          uri: lb://product-cache-service/
          predicates:
            - Path=/api/1.0/product-cache/**
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/api/1.0/user/**
        - id: cart-service
          uri: lb://cart-service/
          predicates:
            - Path=/api/1.0/cart/**
        - id: cart-service
          uri: lb://cart-service/
          predicates:
            - Path=/api/1.0/order/**
info:
  component: Zuul Edge  Server


#server:
#  port: 8762

server:
  port: 4041

endpoints:
  routes:
    sensitive: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            enabled: true
            timeoutInMilliseconds: 60000

---
spring:
  config:
    activate:
      on-profile: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4042/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


---
spring:
  config:
    activate:
      on-profile: stage


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:4042/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${random.uuid}